SELECT * FROM ID;
SELECT * FROM DADOS_MUTUARIOS;
SELECT * FROM EMPRESTIMOS;
SELECT * FROM HISTORICOS_BANCO;

DELETE FROM ID WHERE ID_USUARIO = '';
DELETE FROM DADOS_MUTUARIOS WHERE ID_USUARIO = '';
DELETE FROM EMPRESTIMOS WHERE ID_SOLICITACAO = '';
DELETE FROM HISTORICOS_BANCO WHERE ID_HISTORICO = '';
DELETE FROM DADOS_MUTUARIOS WHERE IDADE > 100;

UPDATE DADOS_MUTUARIOS SET SIT_PROPIEDADE = 'ALUGADA' WHERE SIT_PROPIEDADE = 'RENT';
UPDATE DADOS_MUTUARIOS SET SIT_PROPIEDADE = 'PROPIA' WHERE SIT_PROPIEDADE = 'OWN';
UPDATE DADOS_MUTUARIOS SET SIT_PROPIEDADE = 'HIPOTECADA' WHERE SIT_PROPIEDADE = 'MORTGAGE';
UPDATE DADOS_MUTUARIOS SET SIT_PROPIEDADE = 'OUTROS' WHERE SIT_PROPIEDADE = 'OTHER';
UPDATE HISTORICOS_BANCO SET INADIMPLENCIA = '1' WHERE INADIMPLENCIA = 'Y';
UPDATE EMPRESTIMOS SET MOTIVO = 'PESSOAL' WHERE MOTIVO = 'Personal';
UPDATE EMPRESTIMOS SET MOTIVO = 'EDUCATIVO' WHERE MOTIVO = 'EDUCATION';
UPDATE EMPRESTIMOS SET MOTIVO = 'MEDICO' WHERE MOTIVO = 'MEDICAL';
UPDATE EMPRESTIMOS SET MOTIVO = 'EMPREENDIMENTO' WHERE MOTIVO = 'VENTURE';
UPDATE EMPRESTIMOS SET MOTIVO = 'MELHORA DO LAR' WHERE MOTIVO = 'Homeimprovement';
UPDATE EMPRESTIMOS SET MOTIVO = 'PAGAMENTO DE DEBITOS' WHERE MOTIVO = 'Debtconsolidation';

CREATE TABLE dados_juntos AS SELECT 
B.IDADE, B.SALARIO_ANUAL, UPPER(B.SIT_PROPIEDADE) AS SIT_PROPIEDADE, B.TEMPO_DE_TRABALHO, 
UPPER(C.MOTIVO) AS MOTIVO, C.PONTUACAO_EMPRESTIMO, C.VALOR_TOTAL_SOLICITADO, C.TAXAS_JUROS, C.POSSIB_INADIMPLENCIA, C.RENDA_PERCENTUAL, 
D.INADIMPLENCIA, D.TEMPO_PRIMEIRA_SOL_CRED
FROM ID A
INNER JOIN DADOS_MUTUARIOS B ON B.ID_USUARIO = A.ID_USUARIO
INNER JOIN EMPRESTIMOS C ON C.ID_SOLICITACAO = A.ID_SOLICITACAO
INNER JOIN HISTORICOS_BANCO D ON D.ID_HISTORICO = A.ID_HISTORICO;

SELECT * FROM dados_juntos;

//FIM